"""Unofficial async Python client for the BCS Trade API."""

from __future__ import annotations

from bacsy._json import JsonValue
from bacsy._version import __version__
from bacsy.accounts import Account, AccountManager, TokenRecord
from bacsy.auth import (
    AccessTokenCache,
    AccessTokenProvider,
    DefaultAccessTokenCache,
    FileAccessTokenCache,
    MemoryAccessTokenCache,
    RefreshingAccessTokenProvider,
    RefreshToken,
    StaticAccessTokenProvider,
    TokenScope,
)
from bacsy.client import TradeApiClient
from bacsy.config import (
    DEFAULT_REST_BASE_URL,
    DEFAULT_TIMEOUT_SECONDS,
    DEFAULT_USER_AGENT,
    DEFAULT_WS_BASE_URL,
    TOKEN_ENDPOINT_PATH,
    ClientConfig,
    RateLimitConfig,
    ReconnectPolicy,
    RetryPolicy,
    StreamOptions,
)
from bacsy.exceptions import (
    AccountError,
    AccountExistsError,
    AccountNotFoundError,
    AccountStoreError,
    ApiError,
    AuthenticationError,
    AuthError,
    BacsyError,
    BadRequestError,
    ConfigurationError,
    ConflictError,
    ErrorResponse,
    InvalidTokenError,
    NotFoundError,
    NoUsableTokenError,
    PermissionDeniedError,
    ProtocolError,
    RateLimitError,
    RequestValidationError,
    ServerError,
    StreamLimitError,
    TokenRefreshError,
    TokenRefreshReason,
    TransportError,
    WebSocketClosedError,
    WebSocketConnectError,
)
from bacsy.http import ApiHttpClient, new_http_pool
from bacsy.models import ApiErrorBody, ApiErrorType, BaseApiModel, Reconnected, RequestModel
from bacsy.routes import Operation, Service

__all__ = [
    "DEFAULT_REST_BASE_URL",
    "DEFAULT_TIMEOUT_SECONDS",
    "DEFAULT_USER_AGENT",
    "DEFAULT_WS_BASE_URL",
    "TOKEN_ENDPOINT_PATH",
    "AccessTokenCache",
    "AccessTokenProvider",
    "Account",
    "AccountError",
    "AccountExistsError",
    "AccountManager",
    "AccountNotFoundError",
    "AccountStoreError",
    "ApiError",
    "ApiErrorBody",
    "ApiErrorType",
    "ApiHttpClient",
    "AuthError",
    "AuthenticationError",
    "BacsyError",
    "BadRequestError",
    "BaseApiModel",
    "ClientConfig",
    "ConfigurationError",
    "ConflictError",
    "DefaultAccessTokenCache",
    "ErrorResponse",
    "FileAccessTokenCache",
    "InvalidTokenError",
    "JsonValue",
    "MemoryAccessTokenCache",
    "NoUsableTokenError",
    "NotFoundError",
    "Operation",
    "PermissionDeniedError",
    "ProtocolError",
    "RateLimitConfig",
    "RateLimitError",
    "ReconnectPolicy",
    "Reconnected",
    "RefreshToken",
    "RefreshingAccessTokenProvider",
    "RequestModel",
    "RequestValidationError",
    "RetryPolicy",
    "ServerError",
    "Service",
    "StaticAccessTokenProvider",
    "StreamLimitError",
    "StreamOptions",
    "TokenRecord",
    "TokenRefreshError",
    "TokenRefreshReason",
    "TokenScope",
    "TradeApiClient",
    "TransportError",
    "WebSocketClosedError",
    "WebSocketConnectError",
    "__version__",
    "new_http_pool",
]
